![rmotr](https://i.imgur.com/jiPp4hj.png)
<hr style="margin-bottom: 40px;">

# Numpy additional exercises
![separator2](https://i.imgur.com/4gX5WFr.png)

In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.14.5


![separator1](https://i.imgur.com/ZUWYTii.png)

## Array creation

In [2]:
# Create a numpy array of size 10, filled with zeros.

# Your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# Create a numpy array with values ranging from 10 to 49

# Your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# Create a numpy matrix of 2*2 integers, filled with ones.

# Your code goes here

np.ones([2,2], dtype = 'int')

array([[1, 1],
       [1, 1]])

In [6]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.

# Your code goes here
np.ones([3,2], dtype = 'float')

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
X = np.arange(4, dtype=np.int)

# Your code goes here
np.ones_like(X)

array([1, 1, 1, 1])

In [10]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

# Your code goes here
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
# Create a numpy matrix of 4*4 integers, filled with fives.

# Your code goes here
np.ones([5,5], dtype = np.int)*5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
X = np.array([[2,3], [6,2]], dtype=np.int)

# Your code goes here
np.ones_like(X)*7

array([[7, 7],
       [7, 7]])

In [19]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

# Your code goes here
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Create a numpy array, filled with 3 random integer values between 1 and 10

# Your code goes here
np.random.randint(10,size = 3)

array([2, 6, 0])

In [25]:
# Create a 3*3*3 numpy matrix, filled with random float values

# Your code goes here
np.random.randn(3,3,3)

array([[[-7.44311119e-01,  9.92737180e-02,  2.68293637e-01],
        [ 9.73670227e-04, -5.77325645e-01,  8.66566673e-01],
        [-1.20287194e+00,  7.47257786e-01, -5.05762075e-01]],

       [[ 4.54637049e-01,  2.50557012e-01, -3.33190475e+00],
        [-2.52534042e-02, -2.41036706e+00,  1.04638015e+00],
        [ 5.16180924e-01,  1.01572972e+00, -2.67171290e-01]],

       [[-1.07004679e+00, -3.48856041e+00, -4.83479399e-01],
        [-8.19776294e-01, -8.01834611e-02,  9.96668233e-01],
        [-4.42523891e-01,  4.25654020e-01, -1.66048761e+00]]])

In [29]:
# Given the X python list convert it to an Y numpy array
X = [1, 2, 3]
print(X, type(X))

# Your code goes here
Y = np.array(X)

[1, 2, 3] <class 'list'>


In [32]:
# Given the X numpy array, make a copy and store it on Y.
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

# Your code goes here
Y = X.copy()

print(Y, id(Y))

[5 2 3] 140597760941312
[5 2 3] 140597760963248


In [33]:
# Create a numpy array with numbers from 1 to 10

# Your code goes here

np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# Create a numpy array with the odd numbers between 1 to 10

# Your code goes here

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [38]:
# Create a numpy array with numbers from 1 to 10, in descending order.

# Your code goes here
np.arange(0,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [47]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

# Your code goes here
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
# Show the memory size of the given Z numpy matrix
Z = np.zeros((10,10))

# Your code goes here



![separator1](https://i.imgur.com/ZUWYTii.png)

## Array indexation

In [48]:
# Given the X numpy array, show it's first element
X = np.array(['A','B','C','D','E'])

# Your code goes here
X[0]

'A'

In [50]:
# Given the X numpy array, show it's last element
X = np.array(['A','B','C','D','E'])

# Your code goes here
X[-1]

'E'

In [52]:
# Given the X numpy array, show it's first three elements
X = np.array(['A','B','C','D','E'])

# Your code goes here
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [54]:
# Given the X numpy array, show all middle elements
X = np.array(['A','B','C','D','E'])

# Your code goes here
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [55]:
# Given the X numpy array, show the elements in reverse position
X = np.array(['A','B','C','D','E'])

# Your code goes here
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [58]:
# Given the X numpy array, show the elements in an odd position
X = np.array(['A','B','C','D','E'])

# Your code goes here
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [59]:
# Given the X numpy matrix, show the first row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[0]

array([1, 2, 3, 4])

In [60]:
# Given the X numpy matrix, show the last row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[-1]

array([13, 14, 15, 16])

In [28]:
# Given the X numpy matrix, show the first element on first row
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here

In [61]:
# Given the X numpy matrix, show the last element on last row
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[-1,-1]

16

In [63]:
# Given the X numpy matrix, show the middle row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here

X[1:-1,1:-1]

array([[ 6,  7],
       [10, 11]])

In [65]:
# Given the X numpy matrix, show the first two elements on the first two rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [66]:
# Given the X numpy matrix, show the last two elements on the last two rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[-2:,-2:]

array([[11, 12],
       [15, 16]])

![separator1](https://i.imgur.com/ZUWYTii.png)

## Array manipulation

In [68]:
# Convert the given integer numpy array to float
X = [-5, -3, 0, 10, 40]

# Your code goes here
np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])

In [69]:
# Reverse the given numpy array (first element becomes last)
X = [-5, -3, 0, 10, 40]

# Your code goes here
X[::-1]

[40, 10, 0, -3, -5]

In [72]:
# Order (sort) the given numpy array
X = [0, 10, -5, 40, -3]

# Your code goes here
X.sort()
X

[-5, -3, 0, 10, 40]

In [73]:
# Given the X numpy array, set the fifth element equal to 1
X = np.zeros(10)

# Your code goes here
X[5] = 1
X

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [75]:
# Given the X numpy array, change the 50 with a 40
X = np.array([10, 20, 30, 50])

# Your code goes here
X[-1] = 40
X

array([10, 20, 30, 40])

In [78]:
# Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[-1] = [1,1,1,1]
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [82]:
# Given the X numpy matrix, change the last item on the last row with a 0
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[-1,-1]  = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [83]:
# Given the X numpy matrix, add 5 to every element
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X+5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![separator1](https://i.imgur.com/ZUWYTii.png)

## Boolean arrays _(also called masks)_

In [89]:
# Given the X numpy array, make a mask showing negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X[X<=0]

array([-1,  0, -4,  0,  0, -9])

In [91]:
# Given the X numpy array, get the negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X[X<0]

array([-1, -4, -9])

In [92]:
# Given the X numpy array, get numbers higher than 5
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X[X>5]

array([ 6, 10])

In [93]:
# Given the X numpy array, get numbers higher than the elements mean
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X[X>X.mean()]

array([ 2,  5,  6, 10])

In [94]:
# Given the X numpy array, get numbers equal to 2 or 10
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X[(X == 2) | (X == 10)]

array([ 2, 10])

![separator1](https://i.imgur.com/ZUWYTii.png)

## Logic functions

In [96]:
# Given the X numpy array, return True if none of its elements is zero
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
0 not in X

False

In [97]:
# Given the X numpy array, return True if any of its elements is zero
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
0 in X

True

![separator1](https://i.imgur.com/ZUWYTii.png)

## Summary statistics

In [98]:
# Given the X numpy array, show the sum of its elements
X = np.array([3,5,6,7,2,3,4,9,4])

# Your code goes here
X.sum()

43

In [99]:
# Given the X numpy array, show the mean value of its elements
X = np.array([1,2,0,4,5,6,0,0,9,10])

# Your code goes here
X.mean()

3.7

In [106]:
# Given the X numpy matrix, show the sum of its columns
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
[X.sum(axis = 0)]

[array([28, 32, 36, 40])]

In [107]:
# Given the X numpy matrix, show the mean value of its rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
[X.sum(axis = 1)]

[array([10, 26, 42, 58])]

In [108]:
# Given the X numpy array, show the max value of its elements
X = np.array([1,2,0,4,5,6,0,0,9,10])

# Your code goes here
X.max()

10

![separator2](https://i.imgur.com/4gX5WFr.png)