![rmotr](https://i.imgur.com/jiPp4hj.png)
<hr style="margin-bottom: 40px;">

# Numpy additional exercises - Solution
![separator2](https://i.imgur.com/4gX5WFr.png)

In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.14.1


![separator1](https://i.imgur.com/ZUWYTii.png)

## Array creation

In [2]:
# Create a numpy array of size 10, filled with zeros.

#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# Create a numpy array with values ranging from 10 to 49

np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
# Create a numpy matrix of 2*2 integers, filled with ones.

np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])

In [5]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.

np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
X = np.arange(4, dtype=np.int)

np.ones_like(X)

array([1, 1, 1, 1])

In [7]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
# Create a numpy matrix of 4*4 integers, filled with fives.

np.ones([4,4], dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [10]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Create a numpy array, filled with 3 random integer values between 1 and 10

np.random.randint(10, size=3)

array([4, 2, 2])

In [12]:
# Create a 3*3*3 numpy matrix, filled with random float values

#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[-0.97973969,  0.28436346,  0.4127679 ],
        [ 0.93182446,  0.56970993,  0.27312465],
        [-0.45562671, -0.4805274 ,  0.64108966]],

       [[-1.35332528,  0.85993587, -1.42543822],
        [ 1.31609816, -1.93656726,  1.14410016],
        [ 0.925323  ,  0.02492268,  0.35129241]],

       [[-0.69019773,  0.9184318 , -0.88763382],
        [ 0.12554137, -0.54489263,  1.3596789 ],
        [ 0.86238072, -0.40295541, -0.0870461 ]]])

In [13]:
# Given the X python list convert it to an Y numpy array
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [14]:
# Given the X numpy array, make a copy and store it on Y.
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 4502897248
[5 2 3] 4502897088


In [15]:
# Create a numpy array with numbers from 1 to 10

np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Create a numpy array with the odd numbers between 1 to 10

np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [17]:
# Create a numpy array with numbers from 1 to 10, in descending order.

np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
# Show the memory size of the given Z numpy matrix
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![separator1](https://i.imgur.com/ZUWYTii.png)

## Array indexation

In [20]:
# Given the X numpy array, show it's first element
X = np.array(['A','B','C','D','E'])

X[0]

'A'

In [21]:
# Given the X numpy array, show it's last element
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'

In [22]:
# Given the X numpy array, show it's first three elements
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

In [23]:
# Given the X numpy array, show all middle elements
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [24]:
# Given the X numpy array, show the elements in reverse position
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [25]:
# Given the X numpy array, show the elements in an odd position
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [26]:
# Given the X numpy matrix, show the first row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [27]:
# Given the X numpy matrix, show the last row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

In [28]:
# Given the X numpy matrix, show the first element on first row
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

In [29]:
# Given the X numpy matrix, show the last element on last row
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

In [30]:
# Given the X numpy matrix, show the middle row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [31]:
# Given the X numpy matrix, show the first two elements on the first two rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [32]:
# Given the X numpy matrix, show the last two elements on the last two rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![separator1](https://i.imgur.com/ZUWYTii.png)

## Array manipulation

In [33]:
# Convert the given integer numpy array to float
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])

In [34]:
# Reverse the given numpy array (first element becomes last)
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

In [35]:
# Order (sort) the given numpy array
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

In [36]:
# Given the X numpy array, set the fifth element equal to 1
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [37]:
# Given the X numpy array, change the 50 with a 40
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

In [38]:
# Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [39]:
# Given the X numpy matrix, change the last item on the last row with a 0
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [40]:
# Given the X numpy matrix, add 5 to every element
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![separator1](https://i.imgur.com/ZUWYTii.png)

## Boolean arrays _(also called masks)_

In [41]:
# Given the X numpy array, make a mask showing negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [42]:
# Given the X numpy array, get the negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [43]:
# Given the X numpy array, get numbers higher than 5
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > 5
X[mask]

array([ 6, 10])

In [44]:
# Given the X numpy array, get numbers higher than the elements mean
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

In [45]:
# Given the X numpy array, get numbers equal to 2 or 10
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![separator1](https://i.imgur.com/ZUWYTii.png)

## Logic functions

In [46]:
# Given the X numpy array, return True if none of its elements is zero
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

X.all()

False

In [47]:
# Given the X numpy array, return True if any of its elements is zero
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

X.any()

True

![separator1](https://i.imgur.com/ZUWYTii.png)

## Summary statistics

In [48]:
# Given the X numpy array, show the sum of its elements
X = np.array([3,5,6,7,2,3,4,9,4])

#np.sum(X)
X.sum()

43

In [49]:
# Given the X numpy array, show the mean value of its elements
X = np.array([1,2,0,4,5,6,0,0,9,10])

#np.mean(X)
X.mean()

3.7

In [50]:
# Given the X numpy matrix, show the sum of its columns
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

In [51]:
# Given the X numpy matrix, show the mean value of its rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

In [52]:
# Given the X numpy array, show the max value of its elements
X = np.array([1,2,0,4,5,6,0,0,9,10])

#np.max(X)
X.max()

10

![separator2](https://i.imgur.com/4gX5WFr.png)